# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba69ef9ee7ded8b9e323b6cc7234d00ff52273bcc6dba321874bac2230053a6f9a84c3ecfbb179469830f5ef676242c74fa7106f521f6902df9b971242f0ae08

test:
  secret_key_base: d2e7147e27c270c8885c60e213e9e32d30d267f8b85694cc11530a34c2d3236a9afd679a8f3564a2cfeef5f07653fbcb4871a4356fe3052f909d20fde1cd4692

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
